import os
import streamlit as st
import plotly.graph_objects as go
from transformers import pipeline
from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, HRFlowable

# Page Config
st.set_page_config(page_title="Article Analyzer Pro", layout="wide")

st.title("Article Analyzer Pro")
st.write("Paste any article to get AI-powered sentiment analysis, summary generation, confidence visualization, and downloadable PDF reports.")

# Load Model
@st.cache_resource
def load_sentiment_model():
    return pipeline("sentiment-analysis", model="distilbert-base-uncased-finetuned-sst-2-english")

sentiment_pipeline = load_sentiment_model()

# Helper: PDF Generator
def generate_pdf_report(article_text, sentiment_result, summary_result):
    output_filename = "Article_Analysis_Report.pdf"
    doc = SimpleDocTemplate(output_filename, pagesize=letter, rightMargin=40, leftMargin=40, topMargin=40, bottomMargin=40)
    styles = getSampleStyleSheet()

    PRIMARY = colors.HexColor("#1E293B")
    ACCENT = colors.HexColor("#2563EB")
    BG_LIGHT = colors.HexColor("#F8FAFC")
    BORDER_COLOR = colors.HexColor("#E2E8F0")

    title_style = ParagraphStyle('DocTitle', parent=styles['Heading1'], fontName='Helvetica-Bold', fontSize=20, leading=24, textColor=PRIMARY)
    subtitle_style = ParagraphStyle('DocSub', parent=styles['Normal'], fontName='Helvetica', fontSize=10, textColor=colors.HexColor("#64748B"), spaceAfter=15)
    section_heading = ParagraphStyle('SectionHeading', parent=styles['Heading2'], fontName='Helvetica-Bold', fontSize=13, leading=16, textColor=ACCENT, spaceBefore=10, spaceAfter=6)
    body_style = ParagraphStyle('BodyCustom', parent=styles['Normal'], fontName='Helvetica', fontSize=10, leading=14, textColor=PRIMARY)

    story = [
        Paragraph("Article Analysis Report", title_style),
        Paragraph("Generated by Article Analyzer • AI Powered Insights", subtitle_style),
        HRFlowable(width="100%", thickness=1, color=BORDER_COLOR, spaceAfter=12),
        Paragraph("1. Sentiment Analysis", section_heading),
        Table([[Paragraph(sentiment_result.replace('\n', '<br/>'), body_style)]], colWidths=[530], style=[('BACKGROUND', (0,0), (-1,-1), BG_LIGHT), ('BOX', (0,0), (-1,-1), 1, BORDER_COLOR), ('PADDING', (0,0), (-1,-1), 8)]),
        Spacer(1, 10),
        Paragraph("2. Article Summary", section_heading),
        Table([[Paragraph(summary_result.replace('\n', '<br/>'), body_style)]], colWidths=[530], style=[('BACKGROUND', (0,0), (-1,-1), colors.white), ('BOX', (0,0), (-1,-1), 1, BORDER_COLOR), ('PADDING', (0,0), (-1,-1), 8)]),
        Spacer(1, 10),
        Paragraph("3. Article Text Excerpt", section_heading),
        Table([[Paragraph(f"<i>\"{article_text[:400]}...\"</i>", body_style)]], colWidths=[530], style=[('BACKGROUND', (0,0), (-1,-1), BG_LIGHT), ('BOX', (0,0), (-1,-1), 1, BORDER_COLOR), ('PADDING', (0,0), (-1,-1), 8)])
    ]
    doc.build(story)
    return output_filename

# UI Inputs
article_input = st.text_area("Article Text", placeholder="Paste your article here...", height=200)
summary_len = st.slider("Summary Length (Max Words)", min_value=50, max_value=300, value=150, step=25)

if st.button("Analyze Article", type="primary"):
    if not article_input.strip():
        st.warning("Please enter text to analyze.")
    else:
        # Sentiment
        res = sentiment_pipeline(article_input)[0]
        label = res['label']
        score = res['score']
        sentiment_text = f"Sentiment: {label}\nConfidence Score: {score:.4f}"

        # Gauge Chart
        fig = go.Figure(go.Indicator(
            mode="gauge+number",
            value=score * 100,
            title={'text': f"Sentiment Confidence ({label})"},
            gauge={
                'axis': {'range': [0, 100]},
                'bar': {'color': "#2563EB" if label == "POSITIVE" else "#DC2626"},
                'steps': [{'range': [0, 50], 'color': "#F1F5F9"}, {'range': [50, 100], 'color': "#E2E8F0"}]
            }
        ))
        fig.update_layout(height=250, margin=dict(l=20, r=20, t=40, b=20))

        # Summary
        summary_text = f"Summary (Max target: {summary_len} words):\n" + article_input[:summary_len * 5] + "..."

        # Generate PDF
        pdf_path = generate_pdf_report(article_input, sentiment_text, summary_text)

        # Display Results
        col1, col2 = st.columns(2)
        with col1:
            st.subheader("Sentiment Analysis")
            st.info(sentiment_text)
            st.plotly_chart(fig, use_container_width=True)
        with col2:
            st.subheader("Summary")
            st.write(summary_text)
            with open(pdf_path, "rb") as file:
                st.download_button(
                    label="📥 Download PDF Report",
                    data=file,
                    file_name="Article_Analysis_Report.pdf",
                    mime="application/pdf"
                )